//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43Team11ALibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BookCopies = new HashSet<BookCopy>();
        }
    
        public int BookID { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> PublicationYear { get; set; }
        public string CategoryCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookCopy> BookCopies { get; set; }
        public virtual Category Category { get; set; }
    }
}
