//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43Team11ALibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanTransaction
    {
        public string TransactionID { get; set; }
        public string MemberID { get; set; }
        public System.DateTime DateOFIssue { get; set; }
        public System.DateTime DateDue { get; set; }
        public Nullable<System.DateTime> DateOfReturn { get; set; }
        public string Remarks { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
