//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43Team11ALibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanTransactionLine
    {
        public int TransactionLineID { get; set; }
        public string TransactionID { get; set; }
        public int ISBN { get; set; }
    
        public virtual BookCopy BookCopy { get; set; }
    }
}
